version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: store_mysql
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp
    ports:
      - "3307:3306"
    expose:
      - 3307
    # # It also works
    # volumes:
    #   - ./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    platform: linux/x86_64
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.mysql
    healthcheck:
      test: ["CMD", "/usr/bin/timeout", "5", "mysql", "-h", "mysql", "-u", "root", "-p", "password", "-e", "SELECT 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: store_redis
    ports:
      - 6381:6379
    expose:
      - 6381
